import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { WagmiProvider } from 'wagmi';

import { wagmiConfig } from '@/lib/wagmi';

import '@/assets/styles/globals.css';

// Generated by the TanStack Router Vite plugin from `src/routes` on dev/build.
import { routeTree } from './routeTree.gen';

const router = createRouter({ routeTree });

// Register the router instance type for end-to-end type safety on links/params.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

// A QueryClient tuned for on-chain reads (short stale window, a couple retries).
const queryClient = new QueryClient({
  defaultOptions: { queries: { staleTime: 10_000, retry: 2 } },
});

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error('Root element #root not found');
}

createRoot(rootElement).render(
  <StrictMode>
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </WagmiProvider>
  </StrictMode>,
);
